# Generated by Django 4.2.3 on 2023-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_book_remove_note_owner_userbookrelation_book_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
